# Generated by Django 4.1.7 on 2023-04-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_estado_estado_alter_estado_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='estado',
            new_name='tipo_estado',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
