# Generated by Django 4.1.7 on 2023-04-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_rename_estado_estado_tipo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='tipo_estado',
            field=models.CharField(default='activo', max_length=10),
        ),
    ]
