# Generated by Django 4.1.7 on 2023-04-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_alter_estado_tipo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='tipo_estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10),
        ),
    ]
