# Generated by Django 4.1.7 on 2023-04-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_alter_estado_tipo_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='estado',
            new_name='tipo_estado',
        ),
    ]
